// This is a generated file. Please do not edit.
// See extract_rfp_targets.py, C:/Users/Elmar/Documents/demo32ss/chicken/mozilla-unified/toolkit/components/resistfingerprinting/RFPTargets.inc, C:/Users/Elmar/Documents/demo32ss/chicken/mozilla-unified/toolkit/components/resistfingerprinting/RFPTargetsDefaultBaseline.inc, C:/Users/Elmar/Documents/demo32ss/chicken/mozilla-unified/toolkit/components/resistfingerprinting/RFPTargetsDefault.inc files instead.
export const Targets = {
	"TouchEvents":                               1,
	"PointerEvents":                             2,
	"KeyboardEvents":                            3,
	"ScreenOrientation":                         4,
	"SpeechSynthesis":                           5,
	"CSSPrefersColorScheme":                     6,
	"CSSPrefersReducedMotion":                   7,
	"CSSPrefersContrast":                        8,
	"CanvasRandomization":                       9,
	"CanvasImageExtractionPrompt":               10,
	"CanvasExtractionFromThirdPartiesIsBlocked": 11,
	"CanvasExtractionBeforeUserInputIsBlocked":  12,
	"JSLocale":                                  13,
	"NavigatorAppVersion":                       14,
	"NavigatorBuildID":                          15,
	"NavigatorHWConcurrency":                    16,
	"NavigatorOscpu":                            17,
	"NavigatorPlatform":                         18,
	"NavigatorUserAgent":                        19,
	"PointerId":                                 20,
	"StreamVideoFacingMode":                     21,
	"JSDateTimeUTC":                             22,
	"JSMathFdlibm":                              23,
	"Gamepad":                                   24,
	"HttpUserAgent":                             25,
	"WindowOuterSize":                           26,
	"WindowScreenXY":                            27,
	"WindowInnerScreenXY":                       28,
	"ScreenPixelDepth":                          29,
	"ScreenRect":                                30,
	"ScreenAvailRect":                           31,
	"VideoElementMozFrames":                     32,
	"VideoElementMozFrameDelay":                 33,
	"VideoElementPlaybackQuality":               34,
	"ReduceTimerPrecision":                      35,
	"WidgetEvents":                              36,
	"MediaDevices":                              37,
	"MediaCapabilities":                         38,
	"AudioSampleRate":                           39,
	"NavigatorConnection":                       40,
	"WindowDevicePixelRatio":                    41,
	"MouseEventScreenPoint":                     42,
	"FontVisibilityBaseSystem":                  43,
	"FontVisibilityLangPack":                    44,
	"DeviceSensors":                             45,
	"FrameRate":                                 46,
	"RoundWindowSize":                           47,
	"UseStandinsForNativeColors":                48,
	"AudioContext":                              49,
	"MediaError":                                50,
	"DOMStyleOsxFontSmoothing":                  51,
	"CSSDeviceSize":                             52,
	"CSSColorInfo":                              53,
	"CSSResolution":                             54,
	"CSSPrefersReducedTransparency":             55,
	"CSSInvertedColors":                         56,
	"CSSVideoDynamicRange":                      57,
	"CSSPointerCapabilities":                    58,
	"WebGLRenderCapability":                     59,
	"WebGLRenderInfo":                           60,
	"SiteSpecificZoom":                          61,
	"FontVisibilityRestrictGenerics":            62,
	"WebVTT":                                    63,
	"WebGPULimits":                              64,
	"WebGPUIsFallbackAdapter":                   65,
	"WebGPUSubgroupSizes":                       66,
	"JSLocalePrompt":                            67,
	"ScreenAvailToResolution":                   68,
	"UseHardcodedFontSubstitutes":               69,
	"IsAlwaysEnabledForPrecompute":              0,
	"AllTargets":                                127,
}

export const DefaultTargetsBaseline = {
}

export const DefaultTargetsFPP = {
	"DESKTOP_DEFAULT": ["CanvasRandomization","FontVisibilityLangPack","JSMathFdlibm",],
	"ANDROID_DEFAULT": ["CanvasRandomization","FontVisibilityLangPack","JSMathFdlibm",],
}
